#!/usr/bin/python
# Copyright (c) 2026 Jim Crowley
# GNU General Public License v3.0 or later (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import annotations

DOCUMENTATION = r"""
module: asmb8_auditlog
short_description: Read the ASMB8-iKVM BMC's audit log and its logging configuration
description:
  - >-
    Reads four read-only C(.asp) endpoints: C(getauditlog.asp) (the audit log entries
    themselves), C(getauditlogcfg.asp) (where the audit log is mirrored to -- a remote
    share/SD card), C(getlogcfg.asp) (general audit/syslog enablement and rotation), and
    C(getselcfg.asp) (the IPMI SEL overflow policy).
  - >-
    B(RV(entries) is returned verbatim, and is B(not) sanitised.) Each entry is free text
    generated by BMC firmware describing an operator action -- a login, a configuration
    change, a session event -- and routinely names a real username and a real source
    address, exactly as the fixture corpus's one captured entry does (C(Aug 11 00:48:53
    localhost webgo: [2615 INFO]WEBGUI user admin login successfully from ...)). This
    module does not attempt to redact, truncate, or reinterpret that text: doing so would
    corrupt the record this endpoint exists to provide and give a false sense that
    identifying detail had been removed when a firmware revision this corpus has not seen
    might phrase an entry differently. B(Treat RV(entries) the same way you would treat any
    other export of a real audit trail): do not print it to a public build log, paste it into
    a public issue, or otherwise send it somewhere public without thinking about what a
    specific entry's own text actually contains.
  - >-
    B(A specific parsing hazard this module inherits protection against, not invents.)
    C(tests/unit/fixtures/asp/getauditlog.txt)'s one real captured entry contains the
    literal characters C([) and C(]) B(inside) its own quoted string value
    (C([2615 INFO]) is part of the log line, not array syntax). This module does not parse
    C(.asp) responses itself -- it calls C(module_utils/asp.py)'s C(AspClient.get_webvar()),
    which delegates to C(module_utils/webvar.py)'s quote-aware scanner, the component
    actually responsible for not mistaking that embedded C(]) for the end of the response's
    array. See that module's own docstring for the full sourcing; this module's own tests
    include the exact fixture line to pin the case down at this module's level too, not just
    at the parser's.
  - >-
    B(No credential ever appears in this module's output, by construction.) C(getauditlogcfg.asp)'s
    one record carries a C(PWORD) field for the remote share's own authentication -- this
    module never reads that field into RV(remote_storage), only whether it is non-empty, as
    RV(remote_storage.password_configured). RV(remote_storage.username) is a plain username
    (C(UNAME)), not a password, and is returned as read.
  - >-
    B(RV(remote_storage.address) and RV(logging.remote_syslog_address) are environment detail,
    returned exactly as the BMC reports them, with no redaction performed by this module.) The
    fixture corpus shows both as empty strings (no remote log destination configured on the
    captured board) -- that is not evidence a populated address would look like anything in
    particular. Do not build automation, or a test, that assumes a real address here is
    IPv4-shaped, always populated, or has any other inferred property.
  - >-
    B(This module never writes anything, and there is no option anywhere in it that would.)
    Clearing this BMC's audit log, or changing where it is mirrored to, is B(deliberately
    absent) from this release: a cleared audit log destroys evidence, and there is no way to
    tell, after the fact, whether that was intentional cleanup or exactly the action an
    operator most needed a record of. Adding a write path for either needs its own explicit
    review (who is allowed to clear an audit trail, what confirms the clear actually
    happened, whether the action of clearing it is itself logged somewhere this collection
    can still read) that this module does not attempt to shortcut.
version_added: 0.4.0
author:
  - Jim Crowley (@james-crowley)
extends_documentation_fragment:
  - james_crowley.asmb8_ikvm.connection
seealso:
  - module: james_crowley.asmb8_ikvm.asmb8_alerts
  - module: james_crowley.asmb8_ikvm.asmb8_info
attributes:
  check_mode:
    description: A full read runs identically in check mode, since this module never mutates board configuration.
    support: full
  diff_mode:
    description: Not supported. There is no prior/after state to diff for a read-only module.
    support: none
requirements:
  - requests >= 2.25.0 (on the Ansible controller)
"""

EXAMPLES = r"""
- name: Read the audit log and its logging configuration
  james_crowley.asmb8_ikvm.asmb8_auditlog:
    host: "{{ asmb8_host }}"
    username: "{{ asmb8_username }}"
    password: "{{ asmb8_password }}"
    tls_fingerprint: "{{ asmb8_tls_fingerprint }}"
  delegate_to: localhost
  no_log: true
  register: auditlog

- name: Fail the play if the audit log is disabled
  ansible.builtin.assert:
    that:
      - auditlog.logging.audit_enabled

- name: Do NOT do this in a public-facing log -- entries may contain usernames/addresses
  ansible.builtin.debug:
    msg: "{{ auditlog.entries }}"
  when: false # illustrative only; see this module's description
"""

RETURN = r"""
changed:
  description: Always V(false). This module never mutates anything.
  type: bool
  returned: always
entries:
  description: >-
    Every C(AUDIT_LOG) entry C(getauditlog.asp) returned, in the order reported, exactly as
    written by the BMC. See this module's description: these are B(not) sanitised and may
    contain real usernames or source addresses.
  type: list
  elements: str
  returned: when available
  sample:
    - "Aug 11 00:48:53 localhost webgo: [2615 INFO]WEBGUI user admin login successfully from 192.0.2.10"
remote_storage:
  description: Where the audit log is mirrored to, from C(getauditlogcfg.asp).
  type: dict
  returned: when available
  contains:
    remote_enabled:
      description: Whether mirroring to a remote network share is enabled (C(RM_ENABLE)).
      type: bool
    sd_card_enabled:
      description: Whether mirroring to an SD card is enabled (C(SD_ENABLE)).
      type: bool
    remote_status:
      description: Raw C(REMOTE_STATUS) value.
      type: int
    sd_card_status:
      description: Raw C(SDCARD_STATUS) value.
      type: int
    address:
      description: >-
        Remote share address (C(IP_ADDR)), exactly as reported. Empty string if unset -- see
        this module's description on why this is not redacted and why no shape should be
        assumed for a populated value.
      type: str
    remote_path:
      description: Remote share path (C(REMOTE_PATH)).
      type: str
    share_type:
      description: Raw C(SHR_TYPE) value (the remote share protocol/type code).
      type: int
    username:
      description: Remote share authentication username (C(UNAME)), returned as read. A plain username, not a password.
      type: str
    password_configured:
      description: >-
        Whether C(PWORD) is non-empty, B(not) its value -- see this module's description. The
        actual password is never read into this module's output.
      type: bool
    domain_name:
      description: Remote share authentication domain (C(DOMAIN_NAME)). Empty string if unset.
      type: str
logging:
  description: General audit/syslog enablement and rotation, from C(getlogcfg.asp).
  type: dict
  returned: when available
  contains:
    audit_enabled:
      description: Whether the audit log itself is enabled (C(AUDITENABLE)).
      type: bool
    syslog_enabled:
      description: Whether mirroring to syslog is enabled (C(SYSLOGENABLE)).
      type: bool
    file_size:
      description: Configured maximum log file size in bytes (C(FILESIZE)).
      type: int
    rotate_count:
      description: Configured number of rotated log files retained (C(ROTATECNT)).
      type: int
    remote_syslog_address:
      description: >-
        Remote syslog server address (C(SERVERADDR)), exactly as reported. Empty string if
        unset -- see this module's description on why this is not redacted.
      type: str
sel_policy:
  description: The IPMI SEL (System Event Log) overflow policy, from C(getselcfg.asp) (raw C(SEL_POLICY) value).
  type: int
  returned: when available
operation:
  description: >-
    The non-secret C(asmb8-ikvm-operation/v1) receipt for this read, in the same nested shape every
    other module in this collection returns it under.
  type: dict
  returned: always
  contains:
    schema:
      description: Always V(asmb8-ikvm-operation/v1).
      type: str
    action:
      description: Always V(asmb8_auditlog.read).
      type: str
    endpoint:
      description: The C(host:port) this read was performed against.
      type: str
    changed:
      description: Always V(false).
      type: bool
    error_class:
      description: A stable machine-readable failure class. V(null) on success.
      type: str
    endpoint_reads:
      description: >-
        Per-endpoint outcome for each of the four C(.asp) endpoints this module reads, keyed by
        the RV(entries)/RV(remote_storage)/RV(logging)/RV(sel_policy) field the endpoint feeds.
        Present so a V(null) result can be told apart from "this endpoint genuinely reported
        nothing" versus "the read itself failed for a reason worth seeing" -- a single endpoint
        failing does not fail the whole module once the C(.asp) session itself is established.
      type: dict
      contains:
        outcome:
          description: V(read) if the endpoint was read successfully, V(failed) if the read raised.
          type: str
          choices: [read, failed]
        error_class:
          description: The failure class, on V(failed) only; V(null) otherwise.
          type: str
      sample:
        entries: {outcome: read, error_class: null}
        remote_storage: {outcome: read, error_class: null}
        logging: {outcome: read, error_class: null}
        sel_policy: {outcome: read, error_class: null}
"""

from ansible.module_utils.basic import AnsibleModule, missing_required_lib

from ansible_collections.james_crowley.asmb8_ikvm.plugins.module_utils.asp import HAS_REQUESTS, REQUESTS_IMPORT_ERROR, AspClient
from ansible_collections.james_crowley.asmb8_ikvm.plugins.module_utils.errors import IkvmError
from ansible_collections.james_crowley.asmb8_ikvm.plugins.module_utils.models import OperationReceipt, optional_bool_flag, optional_int, optional_str


def _connection_argument_spec() -> dict[str, dict]:
    return {
        "host": {"type": "str", "required": True},
        "port": {"type": "int", "default": 443},
        "username": {"type": "str", "default": "admin"},
        "password": {"type": "str", "required": True, "no_log": True},
        "use_tls": {"type": "bool", "default": True},
        "allow_insecure_transport": {"type": "bool", "default": False},
        "validate_certs": {"type": "bool", "default": True},
        "ca_path": {"type": "path"},
        "tls_fingerprint": {"type": "str"},
        "timeout": {"type": "int", "default": 30},
        "connect_timeout": {"type": "int", "default": 10},
    }


def argument_spec() -> dict[str, dict]:
    return _connection_argument_spec()


def build_asp_client(params: dict) -> AspClient:
    """Construct an :class:`AspClient` from the module's connection parameters."""
    return AspClient(
        host=params["host"],
        port=params["port"],
        username=params["username"],
        password=params["password"],
        use_tls=params["use_tls"],
        validate_certs=params["validate_certs"],
        ca_path=params["ca_path"],
        tls_fingerprint=params["tls_fingerprint"],
        allow_insecure_transport=params["allow_insecure_transport"],
        timeout=params["timeout"],
        connect_timeout=params["connect_timeout"],
    )


def extract_entries(records: list[dict]) -> list[str]:
    """Pull ``AUDIT_LOG`` text out of every ``getauditlog.asp`` record, verbatim.

    Never rewritten, truncated, or reinterpreted -- see this module's DOCUMENTATION on why
    entries are returned exactly as the BMC wrote them, including any literal ``[``/``]``
    inside the text itself (see ``module_utils/webvar.py`` for the quote-aware scanner that
    already keeps such a value intact through parsing, before this function ever sees it).
    """
    entries = (record.get("AUDIT_LOG") for record in records)
    return [str(entry) for entry in entries if entry is not None]


def build_remote_storage(record: dict) -> dict:
    """Map one ``getauditlogcfg.asp`` record.

    ``PWORD`` is deliberately never read into the returned value -- only whether it is
    non-empty (``password_configured``). See this module's DOCUMENTATION.
    """
    return {
        "remote_enabled": optional_bool_flag(record.get("RM_ENABLE")),
        "sd_card_enabled": optional_bool_flag(record.get("SD_ENABLE")),
        "remote_status": optional_int(record.get("REMOTE_STATUS")),
        "sd_card_status": optional_int(record.get("SDCARD_STATUS")),
        "address": optional_str(record.get("IP_ADDR")) or "",
        "remote_path": optional_str(record.get("REMOTE_PATH")) or "",
        "share_type": optional_int(record.get("SHR_TYPE")),
        "username": optional_str(record.get("UNAME")) or "",
        "password_configured": optional_str(record.get("PWORD")) is not None,
        "domain_name": optional_str(record.get("DOMAIN_NAME")) or "",
    }


def build_logging(record: dict) -> dict:
    return {
        "audit_enabled": optional_bool_flag(record.get("AUDITENABLE")),
        "syslog_enabled": optional_bool_flag(record.get("SYSLOGENABLE")),
        "file_size": optional_int(record.get("FILESIZE")),
        "rotate_count": optional_int(record.get("ROTATECNT")),
        "remote_syslog_address": optional_str(record.get("SERVERADDR")) or "",
    }


def build_sel_policy(record: dict) -> int | None:
    return optional_int(record.get("SEL_POLICY"))


def _read_endpoint(asp: AspClient, reads: dict, *, field: str, endpoint: str, transform):
    """Read one endpoint, degrading a failure to ``None`` rather than failing the whole module.

    Mirrors ``asmb8_alerts.py``'s helper of the same name and ``asmb8_info.py``'s
    ``_read_ipmi_field``: records the outcome in ``reads`` (this module's
    C(operation.endpoint_reads)) and only catches :class:`errors.IkvmError` -- the C(.asp)
    session itself was already established by the time any of these run, so a failure here is
    a per-endpoint refusal, not a connection problem this module should hide.
    """
    try:
        response = asp.get_webvar(endpoint)
        value = transform(response.records)
    except IkvmError as err:
        reads[field] = {"outcome": "failed", "error_class": err.error_class}
        return None
    reads[field] = {"outcome": "read", "error_class": None}
    return value


def gather_auditlog(asp: AspClient) -> tuple[dict, dict]:
    """Read all four endpoints and group them the way this module's RETURN documents.

    Each endpoint degrades independently to ``None`` on failure -- see :func:`_read_endpoint`.
    """
    reads: dict[str, dict] = {}

    entries = _read_endpoint(asp, reads, field="entries", endpoint="getauditlog", transform=extract_entries)
    remote_storage = _read_endpoint(
        asp, reads, field="remote_storage", endpoint="getauditlogcfg", transform=lambda records: build_remote_storage(records[0]) if records else None
    )
    logging_cfg = _read_endpoint(asp, reads, field="logging", endpoint="getlogcfg", transform=lambda records: build_logging(records[0]) if records else None)
    sel_policy = _read_endpoint(
        asp, reads, field="sel_policy", endpoint="getselcfg", transform=lambda records: build_sel_policy(records[0]) if records else None
    )

    result = {
        "entries": entries,
        "remote_storage": remote_storage,
        "logging": logging_cfg,
        "sel_policy": sel_policy,
    }
    return result, reads


def main() -> None:
    module = AnsibleModule(argument_spec=argument_spec(), supports_check_mode=True)

    if not HAS_REQUESTS:
        module.fail_json(msg=missing_required_lib("requests"), exception=REQUESTS_IMPORT_ERROR)
        return

    asp = build_asp_client(module.params)

    try:
        asp.login()
        result, reads = gather_auditlog(asp)
    except IkvmError as err:
        module.fail_json(**err.to_result())
        return

    receipt = OperationReceipt(
        action="asmb8_auditlog.read",
        endpoint=asp.endpoint,
        changed=False,
        extra={"endpoint_reads": reads},
    )
    module.exit_json(
        changed=False,
        entries=result["entries"],
        remote_storage=result["remote_storage"],
        logging=result["logging"],
        sel_policy=result["sel_policy"],
        operation=receipt.to_dict(),
    )


if __name__ == "__main__":
    main()
